from . import gracz as g
from . import enemi as e
from . import umiejetnosci as u
from . import tekst as t
import time
import os

def tekst_do_bitki_wilk():
    print(f"\t {"="*40} \n \t WALKA ROZPOCZYNA SIĘ \n \t {"="*40} \n ")
    time.sleep(1)
    print("\n \t Idąc wąską leśną ścieżką słyszysz cichy szelest w krzakach. \n \t Ptaki nagle milkną, a wiatr porusza gałęziami starych drzew. \n ")
    time.sleep(1)
    print("\t Z ciemności powoli wychodzi lis. \n \n \t Jego futro jest brudne i poszarpane, a oczy świecą dziwnym czerwonym blaskiem.  ")
    time.sleep(1)
    print("\t Zwierz warczy cicho i zaczyna krążyć wokół ciebie.\n ")
    time.sleep(1)
    print("\t To nie wygląda na zwykłego lisa. \n  \n \t Bestia nagle rzuca się w twoją stronę!\n ")
    time.sleep(1)
    print("\n \t Nie wyglada to jak argument do negocjacji.")
    time.sleep(1)
    print(f"\t {"="*40} ")

def kuznia():
    print(f"\t {"="*40} ")
    print("\t Wchodzisz do kuźni. \n \t Powietrze jest gorące, a z każdej strony słychać uderzenia młota o stal.")
    time.sleep(1)
    print("\t Za ladą stoi kowal i wskazuje na wiszące bronie.")
    time.sleep(1)
    print(f"\t {"="*40} ")
    print("\t „Czego potrzebujesz?”")
    time.sleep(1)
    print(f"\t {"="*40} ")
    print("\t [1] Kup broń") 
    time.sleep(1) 
    print("\t [2] Kup zbroję") 
    time.sleep(1)
    print("\t [3] Sprzedaj przedmioty")
    time.sleep(1)  
    print("\t [4] Wyjdź")
    time.sleep(1)
    print(f"\t {"="*40} ")

def misato_wybór():
    print(f"\t {"="*40} ")
    time.sleep(1)
    print("\t [1] Sklep z bronią \n \t Kup miecze, sztylety i lepszy ekwipunek.")
    time.sleep(1)
    print("\t [2] Alchemik \n \t Kup mikstury leczenia i tajemnicze eliksiry.")
    time.sleep(1)
    print("\t [3] Kupiec trofeów \n \t Sprzedaj goblinie uszy, kły i inne potworne części.")
    time.sleep(1)
    print("\t [5] Karczma \n \t Odpocznij, odzyskaj zdrowie i posłuchaj plotek.")
    time.sleep(1)
    print("\t [6] Opuść miasto \n \t Wróć na szlak.")
    time.sleep(1)
    print(f"\t {"="*40} ")

def miasto():
    print(f"\t {"="*40} ")
    time.sleep(1)
    print("\t Po wielu godzinach wędrówki dostrzegasz światła miasta migoczące w oddali. \n \t Kamienne uliczki są mokre po deszczu, a nad dachami unoszą się kłęby dymu z kominów.\n ")
    time.sleep(1)
    print("\t Gdy przechodzisz przez ogromną bramę, uderza cię hałas miasta.\n ")
    time.sleep(1)
    print("\t Kupcy nawołują klientów, dzieci biegają między straganami, a strażnicy obserwują każdego przybysza z ponurymi minami.\n ")
    time.sleep(1)
    print("\t Na środku rynku stoi wielka tablica ogłoszeń pełna zleceń na potwory i bandytów. \n ")
    time.sleep(1)
    print("\t Może da się tu zarobić trochę złota. Albo stracić życie. Miasta zwykle oferują oba pakiety.")
    time.sleep(1)
    print(f"\t {"="*40} ")
    time.sleep(1)

def tekst_do_bitki_goblin():
    print(f"\t {"="*40} \n \t WALKA ROZPOCZYNA SIĘ \n \t {"="*40} \n ")
    time.sleep(1)
    print("\n \t Wchodzisz głębiej w las. Drzewa robią się \n \t gęstsze, a światło znika, jakby ktoś \n ")
    time.sleep(1)
    print("\t powoli wyłączał grafikę w ustawieniach. \n \n \t Nagle słyszysz szelest. \n \n \t Z krzaków wyskakuje goblin. \n ")
    time.sleep(1)
    print("\t Ma krzywy uśmiech, patyk zamiast broni \n \t i minę człowieka, który absolutnie \n ")
    time.sleep(1)
    print("\t nie planuje dziś być rozsądny. \n  \n \t Goblin: \n \t ""REEE!!"" \n ")
    time.sleep(1)
    print("\n \t Nie brzmi to jak argument do negocjacji.")
    time.sleep(1)

def tekst_poczatkowy():
    print(f"\t {"="*40} \n \t KRÓLESTWO FAJTON \n \t {"="*40} \n ")
    time.sleep(1)
    print("\t Budzi cię zimny wiatr i dźwięk dzwonów \n \t z odległego miasta. Plotki mówią, \n ")
    time.sleep(1)
    print("\t że w lasach wokół Fajtonu pojawiły się \n \t potwory oraz dziwne stworzenia.\n ")
    time.sleep(1)
    print("\t Przed tobą stoi stara ścieżka prowadząca\n \t w mrok lasu. Możesz ruszyć na wyprawę\n ")
    time.sleep(1)
    print("\t Przed albo wrócić do bezpiecznego domu,\n \t jak większość ludzi. Taki już gatunek.\n ")
    time.sleep(1)

def teks_z_miejscami():
    print(f"\t {"="*40}")
    print("\t Wybierz co chcesz zrobić:\n ")
    print("\t a - Wyrusz do lasu \n \t i - Idz do miasta \n \t g - Sprawdz stan gracza \n \t q - sprawdz ekwipunek \n \t p - Potki \n \t e - Zakończ wyprawę")
    print(f"\t {"="*40}")


def tekst_do_ruchów():
    print(f"\t {"="*40} \n \t CO ROBISZ? \n \t {"="*40} \n \t a - Atakujesz \n \t o - Odpoczywasz \n \t p - Potki \n \t e - Ucieczka")


def lista_attaków():
    print(f"\t {"="*40} \n \t  1 - Slach \n \t 2 - Heavy Slach \n \t 3 - Kopniecie \n \t {"="*40}")

def wygrałes(gracz,enemy):
    print(f"\t Pokonałes wroga zdobywasz \n \t Gold {enemy["Gold"]} \n \t Loot {enemy["Loot"]}")
    gracz["Gold"] += enemy["Gold"]
    gracz["EQ"].extend(enemy["Loot"])

def alchemik():
    print(f"\t {"="*40}")
    time.sleep(1)
    print("\t Wchodzisz do sklepu alchemika.") 
    time.sleep(1)
    print("\t W powietrzu czuć dziwny zapach ziół i mikstur, a półki są pełne kolorowych butelek.")
    time.sleep(1)
    print("\t Stary alchemik poprawia okulary i patrzy na ciebie.")
    time.sleep(1)
    print("\t „Potrzebujesz leczenia czy czegoś... mocniejszego?”")
    time.sleep(1)
    print("\t [1] Kup potion \n \t [2] Kup eliksiry \n \t [3] Wyjdź")
    time.sleep(1)
    print(f"\t {"="*40}")

def kupca():
    print(f"\t {"="*40}")
    time.sleep(1)
    print("\t Wchodzisz do sklepu handlarza. ")
    time.sleep(1)
    print("\t Na ścianach wiszą potworne kły, rogi i skóry bestii.")
    time.sleep(1)
    print("\t Kupiec uśmiecha się chciwie, widząc twoje łupy.")
    time.sleep(1)
    print("\t„Masz coś ciekawego na sprzedaż?”")
    time.sleep(1)
    print("\t [1] Sprzedaj \n \t [2] Wyjdź")
    time.sleep(1)
    print(f"\t {"="*40}")

def karczma():
    print(f"\t {"="*40}")
    time.sleep(1)
    print("\t Wchodzisz do karczmy. ")
    time.sleep(1)
    print("\t W środku jest głośno, ciepło i trochę za dużo ludzi jak na jeden pokój.")
    time.sleep(1)
    print("\t Barman poleruje kufle, a podróżnicy opowiadają historie, które brzmią jak kłamstwa, ale i tak ktoś je zapisze.")
    time.sleep(1)
    print("\t „Piwo? Pokój? A może plotki?” mruczy karczmarz.")
    time.sleep(1)
    print(f"\t {"="*40}")
    print("\t [1] Odpocznij \n \t [2] Wyjdź")
    time.sleep(1)
    print(f"\t {"="*40}")

def dungeon():
    print(f"\t {"="*40}")
    time.sleep(1)
    print("\t Wybierasz kamienną ścieżkę prowadzącą do dungeona.")
    time.sleep(1)
    print("\t Z każdym krokiem robi się ciszej. Nawet wiatr przestaje brzmieć normalnie.")
    time.sleep(1)
    print("\t Drzewa znikają, a ziemia zamienia się w popękany kamień porośnięty mchem.")
    time.sleep(1)
    print("\t Po kilkunastu minutach marszu widzisz wejście do ruin.")
    time.sleep(1)
    print("\t Ogromny, zniszczony łuk z wyrytymi symbolami, których nie potrafisz odczytać.")
    time.sleep(1)
    print("\t Z wnętrza dochodzi zimny przeciąg.")
    time.sleep(1)
    print("\t Coś tam jest. I nie lubi gości.")
    time.sleep(1)
    print(f"\t {"="*40}")
    print("\t [1] Wejdź do środka \n \t [2] Cofnij się ")
    time.sleep(1)
    print(f"\t {"="*40}")

def dungeon_dalej():
    print(f"\t {"="*40}")
    time.sleep(1)
    print("\t Wchodzisz do środka.")
    time.sleep(1)
    print("\t Powietrze jest wilgotne i ciężkie, jakby samo miejsce oddychało wolniej niż świat na zewnątrz.")
    time.sleep(1)
    print("\t Kroki odbijają się echem od kamiennych ścian.")
    time.sleep(1)
    print("\t Nagle słyszysz szelest kości i cichy jęk.")
    time.sleep(1)
    print("\t Coś się porusza w ciemności.")
    time.sleep(1)
    print(f"\t {"="*40}")
    print("\t [1] Idź dalej \n \t [2] Przygotuj broń \n \t [3] Użyj potion \n \t [4] Cofnij się ")
    time.sleep(1)
    print(f"\t {"="*40}")

def szkelet():
    print(f"\t {"="*40} \n \t WALKA ROZPOCZYNA SIĘ \n \t {"="*40} \n ")
    time.sleep(1)
    print("\t Wchodzisz do kolejnej komnaty lochu. ")
    time.sleep(1)
    print("\t Na ziemi leżą stare kości, porozrzucane jak po dawnej bitwie.")
    time.sleep(1)
    print("\t Kości zaczynają się ruszać.")
    time.sleep(1)
    print("\t Jedna po drugiej składają się w szkielety, chwytając zardzewiałe bronie.")
    time.sleep(1)
    print("\t Puste oczodoły świecą zimnym blaskiem.")
    time.sleep(1)
    print(f"\t {"="*40}")

def zombie():
    print(f"\t {"="*40} \n \t WALKA ROZPOCZYNA SIĘ \n \t {"="*40} \n ")
    time.sleep(1)
    print("\t Schodzisz głębiej do wilgotnego lochu.")
    time.sleep(1)
    print("\t owietrze staje się ciężkie, a ściany pokrywają stare ślady krwi.")
    time.sleep(1)
    print("\t Nagle z ciemności podnoszą się sylwetki — rozkładające się ciała, które nie powinny się już ruszać.")
    time.sleep(1)
    print("\t Nieumarli.")
    time.sleep(1)
    print("\t Ich puste oczy wpatrują się w ciebie, a z ust wydobywa się cichy jęk.")
    time.sleep(1)
    print(f"\t {"="*40}")